In [94]:
import pandas as pd

In [95]:
df=pd.read_csv("Random_Forest_Dataset.csv")
df.head()

,Crop,State,Cost of Cultivation (`/Hectare) A2+FL,Cost of Cultivation (`/Hectare) C2,Cost of Production (`/Quintal) C2,Yield (Quintal/ Hectare)
0,ARHAR,Uttar Pradesh,9794.05,23076.74,1941.55,9.83
1,ARHAR,Karnataka,10593.15,16528.68,2172.46,7.47
2,ARHAR,Gujarat,13468.82,19551.90,1898.30,9.59
3,ARHAR,Andhra Pradesh,17051.66,24171.65,3670.54,6.42
4,ARHAR,Maharashtra,17130.55,25270.26,2775.80,8.72

In [96]:
df.rename(columns={'Cost of Cultivation (`/Hectare) A2+FL':'column2','Cost of Cultivation (`/Hectare) C2':'Cultivation','Cost of Production (`/Quintal) C2':'production','Yield (Quintal/ Hectare) ':'yield'},inplace=True)
df.head()

    Crop           State   column2  Cultivation  production  yield
0  ARHAR   Uttar Pradesh   9794.05     23076.74     1941.55   9.83
1  ARHAR       Karnataka  10593.15     16528.68     2172.46   7.47
2  ARHAR         Gujarat  13468.82     19551.90     1898.30   9.59
3  ARHAR  Andhra Pradesh  17051.66     24171.65     3670.54   6.42
4  ARHAR     Maharashtra  17130.55     25270.26     2775.80   8.72

In [97]:
print(df.columns.tolist())

['Crop', 'State', 'column2', 'Cultivation', 'production', 'yield']

In [98]:
df.drop(['State','column2','yield'],axis='columns',inplace=True)

In [99]:
df.head()

    Crop  Cultivation  production
0  ARHAR     23076.74     1941.55
1  ARHAR     16528.68     2172.46
2  ARHAR     19551.90     1898.30
3  ARHAR     24171.65     3670.54
4  ARHAR     25270.26     2775.80

In [100]:
from sklearn.preprocessing import LabelEncoder

In [101]:
encode=df.copy()
encode.head()

    Crop  Cultivation  production
0  ARHAR     23076.74     1941.55
1  ARHAR     16528.68     2172.46
2  ARHAR     19551.90     1898.30
3  ARHAR     24171.65     3670.54
4  ARHAR     25270.26     2775.80

In [102]:
le_crop=LabelEncoder()

In [103]:
encode['Crop_encode']=le_crop.fit_transform(df['Crop'])
encode.head()

    Crop  Cultivation  production  Crop_encode
0  ARHAR     23076.74     1941.55            0
1  ARHAR     16528.68     2172.46            0
2  ARHAR     19551.90     1898.30            0
3  ARHAR     24171.65     3670.54            0
4  ARHAR     25270.26     2775.80            0

In [104]:
X=encode[['Crop_encode']]
y=encode['production']

In [105]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [106]:
len(X_train)

39

In [107]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [108]:
print("R² score:", model.score(X_test, y_test))

R² score: 0.7456949878824128

In [109]:
y_predicted = model.predict(X_test)

In [110]:
y_predicted

array([1379.87538425,  773.81082246, 1379.87538425, 2256.22555452,
       2183.86484651,  176.40117095,  176.40117095,  883.6343397 ,
        883.6343397 ,  883.6343397 ])